apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: test-tracing-policy
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 1
      type: "file"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/cat"
        - "/bin/cat"
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/passwd"
        - "/etc/shadow"
      matchActions:
      - action: Sigkill