tetragon:
  exportFileCompress: true
  exportAllowList: |-
    {"event_set":["PROCESS_EXEC", "PROCESS_EXIT", "PROCESS_KPROBE", "PROCESS_UPROBE", "PROCESS_TRACEPOINT"], "namespace":["default"]}
  exportDenyList: |-
    {"health_check":true}
  fieldFilters: '{"fields":"process.cwd,process.binary,process.arguments,process.flags,process.start_time,process.pod"}'
  redactionFilters: '{"redact": ["--password(?:\\s+|=)(\\S*)","-p(?:\\s+|=)(\\S*)"]}'

tetragonOperator:
  enabled: false

export:
  mode: ""
