project:
  env: default
  key_directory: ../../../../../../../../../key/key-pair
  auth_directory: ../../../../../../../../../key/auth
  company: example

terraform_config:
  profile: learner
  zone: us-east-1
  bucket: example-default-terraform-state
  dynamodb_table: default-terraform-lock-table
