terraform:
  default:
    profile: learner
    key_directory: ../../../../key/key-pair
    company: example
    env: default
    oidc_issuer: https://git.example.info
helm_repo:
  url: https://charts.example.info
  username: zerak24
  password: 7b9f6844ef1ccf4d23f34ef16490746e78883838
  name: zerak
gitlab:
  url: https://git.example.info
vault:
  url: https://vault.example.info