apiVersion: v1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-cache-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
