controller:

  replicas: 1

  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.14.1

    resources:
      limits:
        cpu: 20m
        memory: 100Mi
      requests:
        cpu: 5m
        memory: 50Mi

  manager:

    image:
      repository: hashicorp/vault-secrets-operator
      tag: 0.1.0

    resources:
      limits:
        cpu: 20m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 50Mi

  controllerConfigMapYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: false
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443

  kubernetesClusterDomain: cluster.local

metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP

defaultVaultConnection:
  enabled: true
  address: "vault.default.svc.cluster.local.:8200" #### config

defaultAuthMethod:
  enabled: false

tests:
  enabled: true
