global:
  storageClass: "standard"
architecture: replicaset
useStatefulSet: true
auth:
  enabled: true
  rottUser: root
  rootPassword: "aef159fae21b953b0b660743bff7603efc3b4444"
  usernames: []
  passwords: []
  databases: []
  replicaSetKey: "f044bd560f6c85549d9e69037578214b25594806"
replicaCount: 1
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
resources:
  limits:
     cpu: 200m
     memory: 500Mi
  requests:
     cpu: 50m
     memory: 100Mi

