{{- if .Values.proxysql_cluster.healthcheck.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}-healthcheck
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
data:
  DB_PASS: {{ .Values.proxysql_cluster.healthcheck.sidecar.config.psql_pass | default "" | b64enc | quote }}
{{- end }}
