project:
  company: example
  env: default
  # key_directory: ../../../../../../../../key/key-pair
  # auth_file: key/auth/auth.yaml

terraform_config:
  zone: us-east5
  project: playground-s-11-1f9cef85
  bucket: example-default-terraform-state-1
