apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
type: application
version: 3.11.0
appVersion: 0.6.4
keywords:
  - kubernetes
  - metrics-server
  - metrics
home: https://github.com/kubernetes-sigs/metrics-server
icon: https://avatars.githubusercontent.com/u/36015203?s=400&v=4
sources:
  - https://github.com/kubernetes-sigs/metrics-server
maintainers:
  - name: stevehipwell
    url: https://github.com/stevehipwell
  - name: krmichel
    url: https://github.com/krmichel
  - name: endrec
    url: https://github.com/endrec
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added default Metrics Server resource requests."
    - kind: changed
      description: "Updated the Metrics Server OCI image to v0.6.3."
    - kind: changed
      description: "Updated the addon resizer OCI image to v1.8.19."
    - kind: changed
      description: "Changed the default addon resizer nanny resource configuration to match the documented Metrics Server autoscaling values."
