kind: DaemonSet
replicaCount: 1
image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag:
  digest:
  pullPolicy: IfNotPresent
testFramework:
  enabled: false
# nodeSelector: {}
# tolerations:
#   - key: "tools"
#     operator: "Equal"
#     value: "true"
config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Exclude_Path *kube-system*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Read_from_Head True

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    # [INPUT]
    #     Name tail
    #     Path /var/run/cilium/tetragon/tetragon.log
    #     Parser docker_no_time
    #     Tag tetragon.*
    #     Mem_Buf_Limit 5MB
    #     Skip_Long_Lines On

  outputs: |
    [OUTPUT]
        Match kube.*
        Name stdout

    # [OUTPUT]
    #     Name http
    #     tls off
    #     Match kube.*
    #     Host clickhouse.log.svc.cluster.local.
    #     Port 8123
    #     URI /?query=INSERT+INTO+fluentbit.kube+FORMAT+JSONEachRow
    #     format json_stream
    #     json_date_key timestamp
    #     json_date_format epoch
    #     http_user default
    #     http_passwd cf13d373b2e8c30bb4216e63c549d71f8e784b62

    # [OUTPUT]
    #     Name http
    #     tls off
    #     Match tetragon.*
    #     Host clickhouse.log.svc.cluster.local.
    #     Port 8123
    #     URI /?query=INSERT+INTO+fluentbit.tetragon+FORMAT+JSONEachRow
    #     format json_stream
    #     json_date_key timestamp
    #     json_date_format epoch
    #     http_user default
    #     http_passwd cf13d373b2e8c30bb4216e63c549d71f8e784b62
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name nest
        Match kube.*
        Operation nest
        Wildcard *
        Nest_under log

    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/functions.lua
        call set_fields

    # [FILTER]
    #     Name lua
    #     Match tetragon.*
    #     script /fluent-bit/scripts/functions.lua
    #     call tetragon_set_fields

luaScripts:
  functions.lua: |
    function set_fields(tag, timestamp, record)
          record['host'] = record['log']['kubernetes']['host']
          record['log']['kubernetes']['host'] = nil
          record['pod_name'] = record['log']['kubernetes']['pod_name']
          record['log']['kubernetes']['pod_name'] = nil
          return 2, timestamp, record
    end
    function tetragon_set_fields(tag, timestamp, record)
        if record['process_exec'] ~= nil then
          record['pod_name'] = record['process_exec']['process']['pod']['name']
          record['process_exec']['process']['pod']['name'] = nil
          record['namespace'] = record['process_exec']['process']['pod']['namespace']
          record['process_exec']['process']['pod']['namespace'] = nil
          record['process'] = record['process_exec']['process']
          record['process_exec'] = nil
        end
        if record['process_exit'] ~= nil then
          record['pod_name'] = record['process_exit']['process']['pod']['name']
          record['process_exit']['process']['pod']['name'] = nil
          record['namespace'] = record['process_exit']['process']['pod']['namespace']
          record['process_exit']['process']['pod']['namespace'] = nil
          record['process'] = record['process_exit']['process']
          record['process_exit'] = nil
        end
        return 2, timestamp, record
    end

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: cilium
    hostPath:
      path: /var/run/cilium
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: cilium
    mountPath: /var/run/cilium
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true