---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  admin_credentials.cnf: {{ tpl (.Files.Get "files/admin_credentials.cnf") . | b64enc }}
  proxysql_admin_user: {{ .Values.secret.admin_user | b64enc }}
  proxysql_admin_password: {{ .Values.secret.admin_password | b64enc }}
{{- if not .Values.ssl.fromSecret -}}
  {{- with .Values.ssl.ca }}
  ca.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.ssl.cert }}
  cert.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.ssl.key }}
  key.pem: {{ . | b64enc }}
  {{- end -}}
{{- end -}}
