{{- range $i, $job := .Values.cronJobs -}}
{{- if $i -}}
---
{{ end -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  namespace:  {{ $.Values.general.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  timeZone: {{ .timeZone | default "Etc/GMT-7" }}
  concurrencyPolicy: Forbid
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "app.serviceAccountName" . }}
          containers:
          - name: {{ .name }}
            image: {{ printf "%s/%s:%s" .Values.image.repository .Values.image.image .Values.image.tag }}
            env:
            {{- range $key, $val := $.Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 200Mi
            command:
            {{ toYaml .command |  indent 12 -}}
          restartPolicy: OnFailure
{{- end }}
