apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.general.fullName }}
  labels:
    app: {{ $.Values.general.fullName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ $.Values.general.fullName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.general.fullName }}
    spec:
      serviceAccountName: {{ $.Values.general.fullName }}
      containers:
        - name: {{ $.Values.general.fullName }}
          image: "{{ $.Values.general.repo }}:{{ $.Values.general.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{ if not $.Values.no_healthcheck -}}
          livenessProbe:
            {{- if hasKey $.Values.livenessProbe "initialDelaySeconds" }}
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            {{- end }}
            {{- if hasKey $.Values.livenessProbe "periodSeconds" }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            {{- end }}
            httpGet:
              path: {{ .Values.health.live | default "/health" }}
              port: {{ .Values.service.name | default "http" }}
              scheme: {{ .Values.service.scheme | default "HTTP" }}
          readinessProbe:
            {{- if hasKey $.Values.readinessProbe "initialDelaySeconds" }}
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            {{- end }}
            {{- if hasKey $.Values.readinessProbe "periodSeconds" }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            {{- end }}
            httpGet:
              path: {{ .Values.health.ready | default "/health" }}
              port: {{ .Values.service.name | default "http" }}
              scheme: {{ .Values.service.scheme | default "HTTP" }}
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
