{{ if .Values.kongIngress.enabled }}
{{- $finalRoutes := .Values.kongIngress.routeMap }}
{{ range $index, $element := $finalRoutes }}

{{ range $element.plugins }}
{{ if eq . "cors" }}
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ $.Values.general.fullName }}-cors-plugin
consumerRef: {{ $.Values.general.fullName }}-consumer-plugin-{{ $.Values.general.namespace }}
plugin: cors
config:
{{ if hasKey $element.cors "origins" }}
  origins:
{{ toYaml $element.cors.origins | indent 4 }}
{{ end }}
{{ if hasKey $element.cors "methods" }}
  methods:
{{ toYaml $element.cors.methods | indent 4 }}
{{ end }}
  headers:
{{ if hasKey $element.cors "headers" }}
{{ toYaml $element.cors.headers | indent 4 }}
{{ else }}
  - "Authorization"
  - "*"
{{ end }}
  credentials: {{ default false $element.cors.credentials }}
  max_age: 3600
  preflight_continue: {{ $element.cors.preflight_continue | default false }}
{{ end }}
{{ end }}


{{ end }}
{{ end }}
