{{- range $index, $element := $.Values.kongIngress.routeMap }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/override: {{ $.Values.general.fullName }}-kong-ingress-configuration-http-{{ $element.name }}
    konghq.com/strip-path: "true"
    konghq.com/method: "POST,GET,PUT,DELETE,OPTIONS,PATCH"
    konghq.com/regex-priority: "0"
    konghq.com/preserve_host: "true"
    konghq.com/protocols: "http,https"
    konghq.com/plugins: {{ include "app.kongpluginingress" $ }}
    configuration.konghq.com: {{ $.Values.general.fullName }}-kong-ingress-configuration-http-{{ $element.name }}
    kubernetes.io/ingress.class: {{ default $.Values.kongIngress.class $element.kongClass }}
  name: {{ $.Values.general.fullName }}-kong-ingress-http-{{ $element.name }}
  namespace: {{ $.Values.general.namespace }}
  labels:
    app: {{ $.Values.general.fullName }}
spec:
  tls:
  - hosts:
{{ toYaml $.Values.kongIngressConfig.domains | indent 4 }}
  rules:
  {{- range $.Values.kongIngressConfig.domains }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          service:
            name: kong-{{ $.Values.general.fullName }}-{{ $element.name }}
            port:
              name: {{ $.Values.service.name | default "http" }}
        path: {{ tpl $element.overridePath $ | default "/" }}
        pathType: ImplementationSpecific
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kong-{{ $.Values.general.fullName }}-{{ $element.name }}
  annotations:
    konghq.com/override: {{ $.Values.general.fullName }}-kong-ingress-configuration-http-{{ $element.name }}
    konghq.com/protocol: http
    konghq.com/path: /
    konghq.com/connect_timeout: "10000"
    konghq.com/retries: "10"
    konghq.com/read_timeout: "10000"
    konghq.com/write_timeout: "10000"
    configuration.konghq.com: {{ $.Values.general.fullName }}-kong-ingress-configuration-http-{{ $element.name }}
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.name | default "http" }}
      protocol: TCP
      name: http
  {{ if $.Values.service.containerGrpcPort }}
    - port: {{ $.Values.service.containerGrpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpclb
  {{end}}
  selector:
    app: {{ $.Values.general.fullName }}
{{- end}}
