apiVersion: v1
kind: Secret
metadata:
  name: role-sync-secrets
data:
  id: NGMzYTAyNDItZmJiMC0yMTk5LTlkZjMtYTBiODQ3ZTdlNTEzCg==
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authen-vault-by-approle
spec:
  method: appRole
  mount: approle
  appRole:
    roleId: 6eed85f2-7adf-6570-ccc6-58bb03c28b05
    secretRef: role-sync-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sync-secret
spec:
  type: kv-v2
  mount: secret
  path: k8s-env
  destination:
    name: k8s-env
    create: true
  refreshAfter: 60s
  vaultAuthRef: authen-vault-by-approle