apiVersion: v1
kind: Secret
metadata:
  name: role-sync-secrets
data:
  id: MWNiOTJkMWEtMTM4Ni1jZjdiLWE3MTAtM2E4MWRiNzgwZjA5Cg==
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authen-vault-by-approle
spec:
  method: appRole
  mount: approle
  appRole:
    roleId: dc18284c-1f56-d9b8-02c6-f1fb2e814aaf
    secretRef: role-sync-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sync-secret
spec:
  type: kv-v2
  mount: secret
  path: k8s-secrets
  destination:
    name: k8s-secret-env
    create: true
  refreshAfter: 60s
  vaultAuthRef: authen-vault-by-approle