resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

tolerations: []

nodeSelector: {}

configuration:
  backupStorageLocation:
  - name:
    provider:
    bucket:
    accessMode: ReadWrite
    config:
      region:

  volumeSnapshotLocation:
  - name:
    provider:
    config:
      region:

  backupSyncPeriod: 5m
  features: EnableCSI,EnableAPIGroupVersions

rbac:
  create: true
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin

serviceAccount:
  server:
    create: true
    # annotations:
