deploy_config:
  namespace: tools
  cluster: minikube
chart:
  repository: zerak/argo-cd
  version: 7.4.4

crds:
  install: false

global:
  logging:
    format: json
    level: warn

configs:
  cm:
    create: true
  params:
    server.insecure: true
  clusterCredentials: #{}
    example-develop-eks:
      server: https://3C22126A35CB688DE618F8406B40168E.gr7.us-east-1.eks.amazonaws.com
      labels: {}
      annotations: {}
      project: default
      config:
        bearerToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IktDUF9QRUhDWThPWThzZjk4XzBfNl9IdmdsUWFJamlNWXloNkJhaG9HV2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0b29scyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtZGVmYXVsdC1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtZGVmYXVsdC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE5MGMyZWZlLTlhYjYtNDAzZi04YzQwLWM1NDUwZDg0MzRhOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp0b29sczphcmdvY2QtZGVmYXVsdC1zYSJ9.Isge0ndr840RGFfS-pNbjxoAxEZSPTdPvDoMQTxNQLewW_Xe_rJzJ_UZZL9vtQlIhNVQGtwHexjMsGhCoXnTi8AlFueMpz8v7DbaLN_Z4FnvPs4joVcCkBqhrNn_W17c0HNixFVguSBfimBUefyU8wb9x5Tjse0MDcnPOnJPJxoyceUeZnsJH1EP0EhPCl6YJS0reU6JMVm3Az3k4K1xNyrjgYosGBXRHvVSDJg10PVQm1riyqfi9XKWDp8qlIoUyVb9QR5OcRS10T7OgIbyb2weCJf_qqrB3rHeglf4I9z0RVwpk2FTGEQ6-nPFfZ5hluzNY7Y43pT9Wq557al_Ug"
        # awsAuthConfig:
        #   clusterName: example-develop-eks
        #   roleARN: "<string>"
        tlsClientConfig:
          insecure: false
          caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS1o2WndzNW1BVlV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1EUXdPVEE1TURGYUZ3MHpOREE1TURJd09URTBNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNoVUhaV0JEM0cyUGJFUFlpa1F3b0czUmNaSjFyV2tNRVR4eDlzWlB4VzZoVkFLdkYzTnRiUitJK0MKYmtFM2l5RUxkNGo4bUExSXRHZ1J1cjYxTzNHU1FwRFVLUmM0dUhqbFNkQ1c2QWt6TzBQUEpUKzJKUkxYOWhibAo3M2QrRzNPN293OUM2ejNMeGUvbFhaZG9WUG5YaVpGZzFTRW1WSTBHOGhRUjFzb1l2SzVKYnpObWI2RHhIb29FCjFrc1dxVno2RldRSnBmdzMzQUl2TE9JMStUSFNFUmFJbldlQzZrai9LMkkrQkNGSTNJb1NoUUE5T3VKbXF2dEEKSzVYbElIMUFNY05qaHRBNldVakpqM1NmTWVMUFNGZkxjK1NwV3d5VFQ2Z3JycWQzeU8weHgra0c4VnRYZFgyUwo1OXBHMjUrNWZ3T2xwZUlMS3pEcnFzUmYrVW0xQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTR3U2SlNObGpzTUdLUzFvcCtHNkFEK3FrcHVqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkJrdExyM2FFTwpic0R6UEVkTDJoUlk3RTdjdHRYSEhGZGk2S2lrc1dmNStIY0FVSFFMdktwRlQ4WW5ER0lnTVVKbmNmVHVtc2x5Ckh6Z3IrelQvVVRxd09kVWhMYnVYVlRIWXRIVzdLeTBpLzRiZHZsd3hsWlQ2alhGZ1BYZE5aekp0M1Eya1RHWEQKaDNXNmVOOWdPZ3RBenAzUXRVcXdRaDZMQ3JZZGUxaDMxaUpRbVFpeUQ1SGJXMnJoS2NZcWtkbjJrdFQ0dW55aQowR2gvTyswQ1lMdjE1NlorcG1RMi8vNjRMVU42NnY4eWZ2SnJmQTZCOUxMNHRRdEFycmhaVVdLS09uQlJ1M2xEClhta3ZHellQN3l0WGxMNkUyWU9XOHQ4dXNpcy8ycG5RcXlkdUIzTk5LQlk4SEowWTBOU3VKeXFPWkVFWlJHVDMKMG5iMXRETWpLMmtjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  repositories:
    helm:
      name: chart-museum
      project: default
      type: helm
      url: http://chartmuseum.default.svc.cluster.local.:8080
      username: zerak24
      password: 7b9f6844ef1ccf4d23f34ef16490746e78883838
    ssh-git-repo:
      url: git@github.com:zerak24/stack.git
      type: git
      name: github
      project: default
      sshPrivateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        ...
        -----END OPENSSH PRIVATE KEY-----
      insecure: "true"

controller:
  name: application-controller
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::992382398009:role/example-default-argocd-management"

dex:
  name: dex-server

redis:
  name: redis
  
server:
  name: server
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::992382398009:role/example-default-argocd-management"
  ingress:
    enabled: false
    hostname: argocd.example.info
    path: /
    pathType: Prefix
    tls: true

repoServer:
  name: repo-server

applicationSet:
  name: applicationset-controller

notifications:
  name: notifications-controller
