apiVersion: v1
kind: Secret
metadata:
  name: chart-museum-repo
  namespace: tools
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: chart-museum
  project: default
  type: helm
  url: http://chartmuseum.default.svc.cluster.local.:8080
  username: zerak24
  password: 7b9f6844ef1ccf4d23f34ef16490746e78883838