deploy_config:
  namespace: tools
  cluster: minikube
chart:
  repo: zerak/argocd
  version: 7.4.4

crds:
  install: false

global:
  logging:
    format: json
    level: warn

configs:
  cm:
    create: true
  params:
    server.insecure: true

controller:
  name: application-controller

dex:
  name: dex-server

redis:
  name: redis
  
server:
  name: server
  ingress:
    enabled: true
    hostname: argocd.example.info
    path: /
    pathType: Prefix
    tls: true

repoServer:
  name: repo-server

notifications:
  name: notifications-controller
