deploy_config:
  namespace: tools
  cluster: minikube
chart:
  repository: zerak/argo-cd
  version: 7.4.4

crds:
  install: false

global:
  logging:
    format: json
    level: warn

configs:
  cm:
    create: true
  params:
    server.insecure: true
  clusterCredentials: #{}
    example-default-eks:
      server: https://B2FCF3CFF199D0D6D095B9FD90F74CA6.gr7.us-east-1.eks.amazonaws.com
      labels: {}
      annotations: {}
      project: default
      config:
        bearerToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlB0RWlhaWFoVUtwRE5zcTVJVDdndHU0WUtaZG9xN3RQdTI2TDc2UG8zSDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ29jZC1kZWZhdWx0LXNhLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFyZ29jZC1kZWZhdWx0LXNhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWIxZjM0NjEtNzNjYi00Nzg2LTljMjYtYmYyYmJkNDAxODQ2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YXJnb2NkLWRlZmF1bHQtc2EifQ.FiWi-KFNKJe-mSf2xp0T2FzSVK45WuR_1v2C4HPw0rSbhMK-iwLguo3AoNdZ0R1HCmdr-ZKAl3BzFTl0vpSSlPhi_Jx_p0oxXOlL1H0oZK6JMUhUFU6T5czLRFskkM5DcjVgezM43Zw2Xt6lZakGE-enzcmB6E2lYCVGo-3YmryOW8DRgErw9w-PJ97l_GTAAQSSPOtRFBqV7W4YcWCGhJjc189PqYF-tahInvPkBxEkNOb1Cl_8juv38JC6ml-oxolmxOGv3Tjt3ZyrclOXhcMB8fDWF2JZRO9Z2S_pyqZEsolLRBNFgfkIdxd3EjA9DDRN6X-IwDO-CRQqj6_c7g"
        # awsAuthConfig:
        #   clusterName: example-develop-eks
        #   roleARN: "<string>"
        tlsClientConfig:
          insecure: false
          caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQkZjSGtVVFhSNEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1EUXhNRFV5TlRaYUZ3MHpOREE1TURJeE1EVTNOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM0NnAwcmdVUm5ySFNSZVJBdmw2ZjhBYXEyZXZaUWxoS0hlaEIxbVNCOFpMQlRvMXVoK1BSTE1IOUYKV20xNllwbXljUlZnZDgxOWpKSVBNV1daRkxyRGZPd2M3SjFYVXhGdTBiZUV1M1FUaGZSTC9Oc2sxR1E3ajE0dwp6a3hiR2hqRk5zRlBPdnJSOW9tSkZITE1abzFreWp4RjNIeU5ERzNla0VZS0hKMngxZHJzdGxjcjVsaEdMZjA4CkdUY2ZyZWxFaVNXeUhyOUs4YTVRVmJ2ck5VaXNIUjdZT1orWE9tWkoxQmIrY2VpNWhET1NkMW95MTl3cTErd0kKT1d6dU5URUI4K2pUcDVxaGJ1blY0Zi9Jbm1iaVJ1STlCeXRKV2lMZk9NYUNmQ3o4bCtRMEFPTDdIVVZVQStXVApjcjBuYlQrS3dvR2l1MUNsanZrODNhNUdRUzloQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTT2xuUTJLclpwUno4RjBZRC9Zc2hzMmdKdXdUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hJWHZQMmt1eAo0TEFXdXBwQkcvM2RwcTc0QnZQczc4dGJFdE4yTHk2WDFKYW5kRnVkQ3NUNE1obTFLRGJNWG9YcnpuSlIvQjFGCnJPdHRLRm1uK0VQbnFiY29NNklPbGRvUHk5T1RSYkRTa0pWTmpIWTNrcmtTZDNNUlBjMzhwSXRLYjlJYU5qN3QKc095Q1BYU1ZEQy93cDBvcHJYK1VVSzBjb1lkSDdpbHJrL2lYRTgxTU51MWhMZVF5bEZmS0QzMUlXbkRPT0w3bQo2MUk4UFlVWXFic21UbzdjdTM3b2NraVVNeWVqbDh6d1U1REZPSnpIMTJ5dlBXZVlJOEhjTHRSNm5oVk5XcFNmCmF3TVR5YmFSN0FTVm9DWEdFYWxzK2tURjQyOUI5Z3dKUDZuaXVlSDdRNzdCVFZpZUs0WFZVeVRWbGtxbjNOdEkKRTdjUjNjR05jMGNNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  repositories:
    helm:
      name: chart-museum
      project: default
      type: helm
      url: http://chartmuseum.default.svc.cluster.local.:8080
      username: zerak24
      password: 7b9f6844ef1ccf4d23f34ef16490746e78883838
    ssh-git-repo:
      url: git@github.com:zerak24/stack.git
      type: git
      name: github
      project: default
      sshPrivateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAgEAvEEnB5E04yP9NvBP2nnGEddL2AaKGFImgkOvfjaMzy0WZ1f8IDxX
        fOhifsJEs9Jp7vmyoNXeA1rkJxRaNq01UOaxnG/qABJ5WvBGopt0ridHGhs+fQ5c+FlJZ7
        w5Al7fspE42QXW0ckfi+GfGzLw11OmSqv7nyMO8688bwlbz6GxKxdAAE5q/UukdRsB1Y9+
        3NoNk/4ulK9PRoiseajpFTUhPdjQY49zjnYf29n1AYta5Wlr3YQ/JFN53c571XnJ8coaJv
        MZoOH1fgfy3boXtxgSGtGfvKybo92wBB1PC80LoQtAPCckYMjE0YeRRfg2ZBrpVZogANiR
        XZHgL5j+zUK94wg1pZZ+dyiHQfed7m8PINd8EVy4qH/D+iP4wsxJABBtLbss5Uk/SN4+mS
        3ujwM3t21inVd44wg+QN08Wa2YUTjyc+9snaV2wcexgYLk5+t2IA/UJH1SYsDkTNk4QRq5
        JwWf9B1kre6kZ7ydWc8wTVZJNmNWtGzPJuRkjJPML/BiusFNB2A+2CchR4i77vQZA+UPdN
        ivMUrh54sVgDXTLuVWrmQOaLgcy+N2UWxfpZoGdaXcoU/0daYAA1ccd1Zw2ABECFRuYPb+
        us8HnNlyjUQrY6fd2leqGa7Wm3M7Nj+FGbbOqQ8NpQB4RE64fG2Y7M+C6c8VlQKw5s/LPb
        8AAAdAfu6V7n7ule4AAAAHc3NoLXJzYQAAAgEAvEEnB5E04yP9NvBP2nnGEddL2AaKGFIm
        gkOvfjaMzy0WZ1f8IDxXfOhifsJEs9Jp7vmyoNXeA1rkJxRaNq01UOaxnG/qABJ5WvBGop
        t0ridHGhs+fQ5c+FlJZ7w5Al7fspE42QXW0ckfi+GfGzLw11OmSqv7nyMO8688bwlbz6Gx
        KxdAAE5q/UukdRsB1Y9+3NoNk/4ulK9PRoiseajpFTUhPdjQY49zjnYf29n1AYta5Wlr3Y
        Q/JFN53c571XnJ8coaJvMZoOH1fgfy3boXtxgSGtGfvKybo92wBB1PC80LoQtAPCckYMjE
        0YeRRfg2ZBrpVZogANiRXZHgL5j+zUK94wg1pZZ+dyiHQfed7m8PINd8EVy4qH/D+iP4ws
        xJABBtLbss5Uk/SN4+mS3ujwM3t21inVd44wg+QN08Wa2YUTjyc+9snaV2wcexgYLk5+t2
        IA/UJH1SYsDkTNk4QRq5JwWf9B1kre6kZ7ydWc8wTVZJNmNWtGzPJuRkjJPML/BiusFNB2
        A+2CchR4i77vQZA+UPdNivMUrh54sVgDXTLuVWrmQOaLgcy+N2UWxfpZoGdaXcoU/0daYA
        A1ccd1Zw2ABECFRuYPb+us8HnNlyjUQrY6fd2leqGa7Wm3M7Nj+FGbbOqQ8NpQB4RE64fG
        2Y7M+C6c8VlQKw5s/LPb8AAAADAQABAAACAEb0E37RpupZfS3Aw4gnz5SX3fks9c2W4PbG
        BhX+/3Fyn/gRfHC17Y+hksYN+JECJHUy3bWrBgOjtUxZamsjO24jlRvOPpcKX3z8BNNy3j
        ZpjW30iMffqwDbvkP/+EjBc3S9MXzyq3XkZSR2xF4fBBFUcN/CFJN1RkRobtG26EjIu5rv
        J2s2IzMW2IReyoEwlXMuKGH4MpxNuwZtqvwrwrYAkWfbGSf9QGOYeAeIDcUoPfkrk8EpAB
        dz8wG7uobKYWflcZfulmFB6SI4YrxZUGjtBJ3hFmCpefv4KUhTt6BOBy0KrYo+goKMCUqj
        2whRNkbiscFW1usatSdcPPATrS0Qfj64QK9eHD+FiDo40FUESvMHELMttq8+IiP2dWDgXY
        S8bzvLbGPlAQVNUtNAzDLjbjBr02HctVtKTwAFGqIMdhReFnM4jRsbXCzT8EvHULjWZb11
        Ql6YXiLghF4TnK+Pze85scAJjf36rRq8f+Fg45bU20q9yPhzGKCKfbGD+oav6TNgejjtWk
        8oDqVl9kP14Q3apS1tP6np0j6tkGLNpHWuQ8nxdeEtbKUawS/fA1ytus/RXZGE6fhP7DU4
        LBNmqQhFzdQ41psqtKge+UAx/B1kTFr6De9/6RGFeteCiwHVFOjSz410cVgWMysB2RDeuf
        CmEVR+pZC1WNdOMkExAAABAQDBdNFH+SBS+DjfaEce8oNwQuiI9R4e4xsbNWIx5vbEyzuE
        KTe8L/R4wcFQ2cp783+BEMgDGazcU1+96rViaSFa7PIXbtnEdOQtn8VWTV91sl5iQuAwfU
        7wGvoRHJ1BjgA7iqQE9v+pXzUNrYIE2NUkYEnwyDD1Ivg7Zd1sv+ifs8tF5cN0RjcReEws
        FAeJ8P+uVXPmjAEQE0FNvEEgKW1Mamvy08nc+RlJrBueHq+t4BkSRm6WDJGkXnMX2dUxdr
        a07C7pQd3JOHR4bsxs1S6zNv4XkWNjlOgBYVfss04nS5mHXCQ4JsnZdPKcw7WsHhr6EFcv
        NHpR+Uz74wnJtBDQAAABAQDUDJnzodBPti9kO28Jn5dIZGxcCtn/+b7yD7jra0KxidQn9h
        lAQeqzznRNXrLrp26GL1+1Te2R6VZKQDFs6tcBunYEz4bQIlKLEdhF4vonsj+difgzYJOL
        nCobK11U72urjLlWIl5jmUBDkGFPZgw6blThfqZXKTN4URUP6CtSmh2it6N33t6o5EwfCU
        KVEteZ1hkhOTeFIiWPoSjIHyVYKrCOFGS2fT0G5ltdpEEpMimDwqeQtCvNj2hXj7x+FqTL
        +cU1AevNoBaeFaHpu+sQQii5kNvvu+aDmZG4eLU+56+Tb+URYsLUxQK6rclE7bY+WTZsU5
        WGPqyJ8KOKF66pAAABAQDjRf7hMvxkZWl7pcEnsbtah0Rv9jmGKVm+xgHZeGVblwVAQi4V
        KaV4jAMGIYySuoBubdFRtSz3oxigvgnsjgDUrbUFaEIGEkJPRKWvJdPGENaZUxozkpZGI6
        wllx9Ldh9VpFl1e9i0b6kRSWKDswzHFdv4sSeJYz0HbTYU98s1cUOUV14zSWTXiATMiMOZ
        zFRXy2xmgle1ZWbrOdu7FcZPBDC/sQ46T7c4D1SzpZ3NBA2F+7KDQBRk5NOpx/ROJzA71v
        YeXaChBJ5C0QC7FFa/GgimfDvEmfNvpxgZOjS1FSmKcbHN3jtQ1ngt0QSj6eZogv3I3afM
        KRcu1GIAQdInAAAACWFyZ29jZEBjaQE=
        -----END OPENSSH PRIVATE KEY-----
      insecure: "true"

controller:
  name: application-controller
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::992382398009:role/example-default-argocd-management"

dex:
  name: dex-server

redis:
  name: redis
  
server:
  name: server
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::992382398009:role/example-default-argocd-management"
  ingress:
    enabled: true
    hostname: argocd.example.info
    path: /
    pathType: Prefix
    tls: true

repoServer:
  name: repo-server

applicationSet:
  name: applicationset-controller

notifications:
  name: notifications-controller
