deploy_config:
  namespace: tools
  cluster: arn:aws:eks:us-east-1:211125606152:cluster/example-default-eks
chart:
  repository: zerak/argo-cd
  version: 7.4.4

crds:
  install: false

global:
  logging:
    format: json
    level: warn

configs:
  cm:
    create: true
  params:
    server.insecure: true
  clusterCredentials: #{}
    example-develop-eks:
      server: https://64F1BD1E2FADCE15181B9E5DEDF26805.gr7.us-east-1.eks.amazonaws.com
      labels: {}
      annotations: {}
      project: default
      config:
        # bearerToken: "<authentication token>"
        awsAuthConfig:
          clusterName: example-develop-eks
          roleARN: "<string>"
        tlsClientConfig:
          insecure: false
          caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYzNzQzQ5OGNndzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1ETXhNekU1TkRkYUZ3MHpOREE1TURFeE16STBORGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURzZkFCMFMwditkNHg2T2xQQXQwaGZRaU5aeDlNcVVKN3V4dTFEanEweE9HRWpxUktyRVhadHN4R3IKOG95UEhibEwwa0g4ZmYzcDVmUVdiS0wyaytlanB3ZkhYSG9KM0dPUjZuZXFidVJWM3R0ODJsMjJ2OFBHZnNzSQpMVG1hWHQ3MXAwMjREd0RacGQ5bVdrVUpLa3ZBanFzZ2RFQ1hYQjQvTDRvcmRHd0pJWVVLVi9jOXJTZDJ3M2VBClRXczNLdGlOWVhXVUV4bkRReHFkMmUvbjJpZFlOZEpkcWYxdytwMFI5YWNHZTdXbEFldStZUUp5WE1wZHdhUnoKa0tZT2pJSTBCNjlWOXcxaU14ZEtOV3RaTUxJNUhiT2FML3BjS0wzSmZ2ZVh1RFZFZVFwcEdzb2FHQnlOejMwdQpOcUk5bnUrL0tUWC9tUG5hN1U5MWJSSGhSUDdmQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJROSs4V3k5bklHTE5WWFJOKzNtNFNSakNGMTlqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnZQdEM1am0wLwpnbXVQdUZ5aG5QdlFvSzRnbzFoenhyWU5EVEdWa0NqempKWE1uSWsrUUIyb3VES3JiS1lETEYyYjI2d0ZlNEd6CmRtczI2RnV0eWk0UmgyOVpUTTdsbjhma3R3WExoQW9WeUZHZ2NIWHlPRXRsSWJUMUpXc3RRaThTMVZBSEJFaHUKSWsybEtBZm9tZ2pZR24zMit4OGVYMWgwNW5XUGZ5WnIxeGJtc29VK2I2U1FmazIrcDZFNXByNmhEOHJsRmt5TQpnbjhkRXMxUStYaS91cGxRbkJjNXFLS0tocjBaOUd3U0ZqQXNmVzdWbFMwc0krUzJuZ1ZhS0h1OEJ4a0MxSkx1Clgwam0zS0VYa28zVTl4RWFvUkdHL2dlWTNpai9CeG0yT01qVzN5T2RjejJLUHlZdUVWY3B6a2tjd0JSclVZZEgKbmcwYWIwTGpCUVlQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  repositories:
    helm:
      name: chart-museum
      project: default
      type: helm
      url: http://chartmuseum.default.svc.cluster.local.:8080
      username: zerak24
      password: 7b9f6844ef1ccf4d23f34ef16490746e78883838
    ssh-git-repo:
      url: git@github.com:zerak24/stack.git
      type: git
      name: github
      project: default
      sshPrivateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        ...
        -----END OPENSSH PRIVATE KEY-----
      insecure: "true"

controller:
  name: application-controller
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::211125606152:role/example-default-argocd-management"

dex:
  name: dex-server

redis:
  name: redis
  
server:
  name: server
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::211125606152:role/example-default-argocd-management"
  ingress:
    enabled: true
    hostname: argocd.example.info
    path: /
    pathType: Prefix
    tls: true

repoServer:
  name: repo-server

applicationSet:
  name: applicationset-controller

notifications:
  name: notifications-controller
